
ALTER TABLE users ADD COLUMN full_name VARCHAR(200);
ALTER TABLE users ADD COLUMN birth_date DATE;
ALTER TABLE users ADD COLUMN phone VARCHAR(30);
ALTER TABLE users ADD COLUMN bio TEXT;
ALTER TABLE users ADD COLUMN updated_at TIMESTAMP DEFAULT NOW();
